### ISSUE TITLE
SyntaxError: Unexpected token '.' on w/ v7.0.0 upwards

### ISSUE THREAD

**Issue by charyeezy** [readmeio/rdme#482]
```
❯ npx rdme docs ../docs/ --version=1.4.5 --key xxx --dryRun
.../docs/node_modules/rdme/bin/rdme:23
    if (err?.message) {
            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Running on
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

**Comment by erunion** [comment]
Are you running Node 12? Node 12 doesn't support optional chaining and we've dropped support for Node 12 with `rdme@7.0.0`.

**Comment by charyeezy** [comment]
Hello! Yes I upgraded to Node 16 and it was resolved thank you @erunion ! 

```
❯ node --version                                                                                                                                                                                                                       L 0.11 ─╯
v16.14.2
```
