### ISSUE TITLE
Jest coverage is broken in GitHub Actions

### ISSUE THREAD

**Issue by kanadgupta** [readmeio/rdme#617]
Been seeing this error when running tests in GitHub Actions CI for a bit now:

```
        Failed to write coverage reports:
        ERROR: Error: ENOENT: no such file or directory, open '/home/runner/work/rdme/rdme/coverage/coverage-final.json'
        STACK: Error: ENOENT: no such file or directory, open '/home/runner/work/rdme/rdme/coverage/coverage-final.json'
    at Object.openSync (fs.js:498:3)
    at FileWriter.writeFile (/home/runner/work/rdme/rdme/node_modules/istanbul-lib-report/lib/file-writer.js:185:41)
    at JsonReport.onStart (/home/runner/work/rdme/rdme/node_modules/istanbul-reports/lib/json/index.js:17:45)
    at Visitor.value (/home/runner/work/rdme/rdme/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportTree.visit (/home/runner/work/rdme/rdme/node_modules/istanbul-lib-report/lib/tree.js:126:17)
    at JsonReport.execute (/home/runner/work/rdme/rdme/node_modules/istanbul-lib-report/lib/report-base.js:12:44)
    at /home/runner/work/rdme/rdme/node_modules/@jest/reporters/build/CoverageReporter.js:241:12
    at Array.forEach (<anonymous>)
    at CoverageReporter.onRunComplete (/home/runner/work/rdme/rdme/node_modules/@jest/reporters/build/CoverageReporter.js:229:25)
    at ReporterDispatcher.onRunComplete (/home/runner/work/rdme/rdme/node_modules/@jest/core/build/ReporterDispatcher.js:71:9)
```

Not sure why, but jest coverage started breaking somewhere between [this commit](https://github.com/readmeio/rdme/pull/577/commits/ca998bc2fae30319a7d85ced85e0f83494fcd221) and [this commit](https://github.com/readmeio/rdme/pull/577/commits/65a209a40981e55db0c861ce53aafbd290501f84).

Anything weird jumping out here? 🧐 https://github.com/readmeio/rdme/compare/ca998bc2fae30319a7d85ced85e0f83494fcd221...65a209a40981e55db0c861ce53aafbd290501f84

See #701 #611 #610 for various attempts to address this.

**Comment by erunion** [comment]
Weird that `rdme` is in there twice:

```
/home/runner/work/rdme/rdme/coverage/coverage-final.json
```

Have you tried setting a `coverageDirectory` into the Jest config? https://jestjs.io/docs/configuration/#coveragedirectory-string

**Comment by kanadgupta** [comment]
I messed around in https://github.com/readmeio/rdme/pull/701 and I think the double `/rdme/rdme` thing is expected? I tried a few values for `coverageDirectory` and that didn't appear to work either 😞
